---
title: "Cyagersz_11"
author: "Cole Yagersz"
output: html_document
---

## Introduction

AP is a shipping service that guarantees overnight delivery of packages in the continental US.The company has various hubs at major cities and airports across the country. Packages are
received at hubs, and then shipped to intermediate hubs or to their final destination.
The manager of the AP hub in Cleveland is concerned about labor costs, and is interested in
determining the most effective way to schedule workers. The hub operates seven days a week,
and the number of packages it handles varies from one day to another.Package handlers at AP are guaranteed a five-day work week with two consecutive days off. The base wage for the handlers is $750 per week. Workers working on Saturday or Sunday receive an
additional $25 per day. 


```{r}
# Load library
library(lpSolve)
library(lpSolveAPI)

rd <- read.lp("Shipping.lp")
rd

solve(rd)

cat("Objective Value:", get.objective(rd), "\n")
cat("Variable Values:\n")
print(get.variables(rd))
```
## Conclusion

Based on what we have found the total cost of the optimal solution is going to be $25,675. The available workers for each day is for shift 1 it is 5 workers, shift 2 is 1 worker, shift 3 is 5 workers, shift 4 is 0 workers, shift 5 is 8 workers, shift 6 is 4 workers, shift 7 is 10 workers. This means Saturday has 19 workers, Sunday has 18 workers, Monday has 27 workers, Tuesday has 27 workers, Wednesday has 28 workers, Thursday has 25 workers, and Friday has 21 workers.